name: Release and Update Docs

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Clone the docs repo
      - name: Clone docs repo
        run: |
          git clone https://github.com/aria-ease/aria-ease-website.git
        
      # Copy CHANGELOG.md to docs repo
      - name: Copy changelog
        run: |
          cp CHANGELOG.md aria-ease-website/CHANGELOG.md

      # Commit and push to docs repo
      - name: Commit and push changelog to docs repo
        run: |
          cd aria-ease-website
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog from library repo"
          git push https://x-access-token:${{ secrets.DOCS_REPO_TOKEN }}@github.com/aria-ease/aria-ease-website.git HEAD:main
